repeat wait() until game:IsLoaded()
game:GetService("RunService"):Set3dRenderingEnabled(false)
task.wait(1)
loadstring(game:HttpGet(('https://raw.githubusercontent.com/ReQiuYTPL/hub/main/ReQiuYTPLHub.lua'),true))()
--loadstring(game:HttpGet("https://raw.githubusercontent.com/IceMae17/NewIceHub/main/Brookhaven"))()
